# Generated by Django 4.2 on 2024-03-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "address",
                    models.CharField(blank=True, max_length=256, verbose_name="Адрес"),
                ),
                (
                    "postcode",
                    models.CharField(
                        blank=True, max_length=16, verbose_name="Почтовый индекс"
                    ),
                ),
            ],
            options={
                "verbose_name": "Организация",
                "verbose_name_plural": "Организации",
            },
        ),
    ]
