# Generated by Django 4.2 on 2024-03-13 16:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="employees",
            field=models.ManyToManyField(
                related_name="employees", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
