# Generated by Django 4.2 on 2024-03-13 16:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_organization"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="organization",
        ),
    ]
