# Generated by Django 4.2 on 2024-03-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("image", models.ImageField(upload_to="", verbose_name="Изображение")),
                (
                    "date",
                    models.DateTimeField(blank=True, verbose_name="Дата проведения"),
                ),
                (
                    "organizations",
                    models.ManyToManyField(
                        related_name="organizations", to="organizations.organization"
                    ),
                ),
            ],
            options={
                "verbose_name": "Мероприятие",
                "verbose_name_plural": "Мероприятия",
                "ordering": ["date"],
            },
        ),
    ]
